require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
